### PR TITLE
Add the new 'smart' implementation of Composer's class loader

### PR DESCRIPTION
**Pull request by donquixote**
Composer class loader has changed.
https://github.com/composer/composer/commit/94175ce432e30712fa46ceff1fdee49727542263
It checks the first character of a class, to pre-select prefixes. This is cool!

Adding a "ComposerSmart" class to reflect the changes, and to allow comparison with the old version.

### CODE REVIEW

**Comment by donquixote** [comment]
Results are nice.

```
> classmap:      2.601810ms (1.00x)
> apc:           4.034173ms (1.55x)
> composersmart: 28.709726ms (11.03x)
> composer:      60.824232ms (23.38x)
> psr0:          61.200621ms (23.52x)
```

**Comment by donquixote** [comment]
With this technique, it will become relevant if we have a lot of stuff registered for the same top-level namespace.
E.g. in Drupal we'd typically have

```
Drupal\system -> modules/system/lib
Drupal\node -> modules/node/lib
Drupal\user -> modules/user/lib
...
```

The optimization won't help if all registered namespaces start with the same character.

I suggest to add a variation of the scenario where a lot of registered namespaces have the same starting character. And then we have to evenly distribute the classes ..

**Comment by donquixote** [comment]
To actually make this work in combination with https://github.com/Seldaek/autoload-bench/pull/6 (prefix variations), some further changes to ComposerSmart are needed.

I will wait for feedback on the other pull requests, then I can make a new one where I combine stuff.

**Comment by Seldaek** [comment]
I merged #6 if you want to try to apply changes to this code, but maybe it'd be best to merge it as is so the PR can be compared against master. But I am not sure it's possible to optimize for the `Drupal\...` case. What I figured is that most of the Drupal code will be in only a few packages, so even if that's many more classes it's ok because it'll hit the paths['D'] and that only contains a few dirs to loop through. This is probably not always true, and there can be best and worst case scenarios for sure, but on average it yields much better results than not doing this step I think.

**Comment by donquixote** [comment]
> What I figured is that most of the Drupal code will be in only a few packages, so even if that's many more classes it's ok because it'll hit the paths['D'] and that only contains a few dirs to loop through.

What did you look at?
The compiled core/vendor/composer/autoload_namespaces.php in Drupal does indeed only contain Drupal\Core and Drupal\Component.
But then you add core modules, which add e.g. Drupal\system, Drupal\views, etc.
And then you add contrib modules and themes, which again add Drupal\devel, etc.
I just checked two D7 sites which both have around 150 modules. Not unusual at all.
Granted, not all of these modules have a lot of classes. But you also never know for sure in which order they are registered.

None of this goes into autoload_namespaces.php, it is added dynamically after bootstrap.
Therefore, the change proposed here may not really help in the Drupal case, because Composer does not know that so many Drupal namespaces are going to follow.

I just thought there might be other projects with the same problem. And in the Drupal case, Drupal could put a hint in the composer.json?

**Comment by donquixote** [comment]
This being said, I have no problem with Drupal having its own optimized class loader, or use something 3rd party. It is just that most others want to have an original Composer-branded loader.

Drupal has a long history of doing its own thing, now it is turning in the opposite direction. Maybe a middle ground would be the better choice.

**Comment by Seldaek** [comment]
Well what I'm thinking is that modules shouldn't really be in the drupal namespace to begin with. Except for a few core-maintained ones (though I guess a few for drupal means 100s:). Anyway it's hard to say if doing a second-level check (like check the first letter of the second namespace bit) will be faster than not doing it. Obviously in cases where there is only one namespace in the first-level letter you only waste time, but in cases like drupal you might save time if you do less filesystem checks..

**Comment by donquixote** [comment]
Just a quick note (probably you are aware of it): This particular PR only does the first-character check that is already in Composer.

Together with the other PR, it confirms the observation that this optimization does not really help if all prefixes have the same first character. Which is not really surprising.

So, if I understand correctly, I'm going to merge this thing with updated master. (going to do that)

**Comment by donquixote** [comment]
> Anyway it's hard to say if doing a second-level check (like check the first letter of the second namespace bit) will be faster than not doing it. Obviously in cases where there is only one namespace in the first-level letter you only waste time, but in cases like drupal you might save time if you do less filesystem checks..

This is why I made a benchmark :)
https://github.com/donquixote/autoload-bench/issues/1

**Comment by donquixote** [comment]
Sorry, now I don't remember what I need to add there :/

**Comment by Seldaek** [comment]
Well I guess it's mergeable as is isn't it? I mean it just adds the current composer implementation or did I get it wrong?

**Comment by donquixote** [comment]
Found it!

**Pull request merged**
